version: '3'
services:
  web:
    image: 185513101483.dkr.ecr.us-east-1.amazonaws.com/app:v1.2
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options: 
        awslogs-group: app
        awslogs-region: us-east-1
        awslogs-stream-prefix: app
